#!/usr/bin/env python3
"""Generate Chapter 02 notebook: Core Agentic Architectures and Mechanisms.

Uses list-of-lines approach to avoid triple-quote conflicts with docstrings.
"""

import json
import pathlib


def md(source: str) -> dict:
    return {
        "cell_type": "markdown",
        "metadata": {},
        "source": source.strip().splitlines(keepends=True),
    }


def code(source: str) -> dict:
    return {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": source.strip().splitlines(keepends=True),
    }


cells = []

# ═══════════════════════════════════════════════════════════════════════════════
# Cell 0 — Title (markdown)
# ═══════════════════════════════════════════════════════════════════════════════
cells.append(md(
'# Chapter 2: Core Agentic Architectures and Mechanisms\n'
'\n'
'> *"The difference between a demo agent and a production agent is architecture."*\n'
'\n'
'---\n'
'\n'
'**Course:** Production-Grade Multi-Agent Systems for Analog Electronic Design Automation  \n'
'**Level:** PhD / Advanced Professional  \n'
'**Prerequisites:** Chapter 1 — Foundations: AI4EDA → Agentic EDA\n'
'\n'
'In this chapter we move from *what* agentic EDA is to *how* it is structured internally.\n'
'We will study **four canonical multi-agent design patterns**, implement each in\n'
'production-quality Python, and then combine them into **hybrid architectures**\n'
'that mirror real tape-out workflows.\n'
'\n'
'| Symbol | Meaning |\n'
'|--------|--------|\n'
'| $\\mathcal{A}$ | An autonomous agent |\n'
'| $\\mathcal{S}$ | The shared state (blackboard) |\n'
'| $m_{ij}$ | A typed message from agent $i$ to agent $j$ |\n'
'| $\\text{PPA}$ | Power · Performance · Area figure-of-merit |\n'
'\n'
'### Chapter Roadmap\n'
'\n'
'| § | Topic | Key Artefact |\n'
'|---|-------|-------------|\n'
'| 2.1 | Introduction to MAS Design Patterns | Taxonomy table |\n'
'| 2.2 | Supervisor-Worker Architecture | `SupervisorAgent` / `WorkerAgent` classes |\n'
'| 2.3 | Consensus-Based Reasoning | Radar-chart PPA comparison |\n'
'| 2.4 | Handoff Pattern | State-machine diagram |\n'
'| 2.5 | Stateful Graph Workflows (DAGs & Cycles) | Interactive DAG of an analog flow |\n'
'| 2.6 | Hybrid Architectures | Combined topology diagram |\n'
'| 2.7 | Agent Communication Protocols | Pydantic message bus |\n'
'| 2.8 | Practical Exercise — Mini Analog Design MAS | End-to-end pipeline with `rich` output |\n'
))

# ═══════════════════════════════════════════════════════════════════════════════
# Cell 1 — Imports (code)
# ═══════════════════════════════════════════════════════════════════════════════
cells.append(code(
'# ──────────────────────────────────────────────────────────────\n'
'#  Standard & third-party imports used throughout this chapter\n'
'# ──────────────────────────────────────────────────────────────\n'
'from __future__ import annotations\n'
'\n'
'import enum\n'
'import json\n'
'import math\n'
'import random\n'
'import textwrap\n'
'import uuid\n'
'from abc import ABC, abstractmethod\n'
'from dataclasses import dataclass, field\n'
'from datetime import datetime, timezone\n'
'from typing import Any, Callable, Optional\n'
'\n'
'import matplotlib.pyplot as plt\n'
'import matplotlib.patches as mpatches\n'
'import networkx as nx\n'
'import numpy as np\n'
'import plotly.graph_objects as go\n'
'from pydantic import BaseModel, Field\n'
'\n'
'random.seed(42)\n'
'np.random.seed(42)\n'
'\n'
'print("All imports successful — Chapter 2 environment ready.")\n'
))

# ═══════════════════════════════════════════════════════════════════════════════
# Cell 2 — Section 2.1 intro (markdown)
# ═══════════════════════════════════════════════════════════════════════════════
cells.append(md(
'---\n'
'\n'
'## 2.1 Introduction to MAS Design Patterns for EDA\n'
'\n'
'### Why patterns matter in production systems\n'
'\n'
'In software engineering, *design patterns* (Gamma et al., 1994) capture proven solutions\n'
'to recurring structural problems.  The same principle applies to **multi-agent systems\n'
'(MAS)**: without an explicit architecture, agent interactions devolve into an\n'
'unmanageable tangle of ad-hoc calls.\n'
'\n'
'> **Observation (Informal).** Let $n$ be the number of agents.  In a fully-connected\n'
'> unstructured MAS the number of pairwise communication channels grows as\n'
'> $$C = \\binom{n}{2} = \\frac{n(n-1)}{2}$$\n'
'> For $n = 8$ specialist agents this yields $C = 28$ channels — each a potential source\n'
'> of race conditions, stale state, or contradictory instructions.\n'
'\n'
'### The cost of unstructured agent interactions\n'
'\n'
'| Problem | Manifestation in EDA |\n'
'|---------|---------------------|\n'
'| **Message explosion** | Every agent broadcasts every SPICE result to all peers |\n'
'| **Circular reasoning** | Sizing agent and topology agent endlessly revise each other |\n'
'| **No single source of truth** | Conflicting PPA numbers stored in different agent memories |\n'
'| **Untraceable decisions** | Post-silicon failure analysis cannot identify which agent chose a weak topology |\n'
'| **Lack of reproducibility** | Non-deterministic message ordering changes the final netlist |\n'
'\n'
'The four patterns we study next impose **structured communication topologies** that\n'
'eliminate or bound these failure modes.\n'
'\n'
'> **Key Insight:** A well-chosen architecture does not constrain creativity —\n'
'> it *channels* it through verifiable, auditable pathways.\n'
))

# ═══════════════════════════════════════════════════════════════════════════════
# Cell 3 — Section 2.2 intro (markdown)
# ═══════════════════════════════════════════════════════════════════════════════
cells.append(md(
'---\n'
'\n'
'## 2.2 Pattern 1 — Supervisor-Worker Architecture\n'
'\n'
'### Concept\n'
'\n'
'A single **Supervisor Agent** (backed by a frontier model such as GPT-5.2 or\n'
'Claude 4.5 Opus) receives high-level design intent from the user and\n'
'**decomposes** it into discrete, parallelisable sub-tasks.  Each sub-task is\n'
'dispatched to a **Worker Agent** that is a specialist (synthesis, DFT,\n'
'physical design, etc.).\n'
'\n'
'$$\n'
'\\text{Supervisor}: \\; \\mathcal{I} \\;\\longrightarrow\\; \\{t_1, t_2, \\ldots, t_k\\}\n'
'\\quad\\text{where each } t_i \\text{ is assigned to worker } w_i\n'
'$$\n'
'\n'
'**Properties:**\n'
'\n'
'| Property | Value |\n'
'|----------|-------|\n'
'| Topology | Star (hub-and-spoke) |\n'
'| Control flow | Centralised |\n'
'| Failure handling | Supervisor retries / reassigns |\n'
'| Scalability | $O(k)$ — linear in number of workers |\n'
'\n'
'### Example Decomposition\n'
'\n'
'> **User prompt:** *"Implement a low-power RISC-V core in 7 nm."*\n'
'\n'
'The supervisor decomposes this into:\n'
'\n'
'1. **Synthesis Agent** → RTL → gate-level netlist  \n'
'2. **DFT Agent** → scan-chain insertion, ATPG  \n'
'3. **STA Agent** → timing closure at all corners  \n'
'4. **Power Agent** → UPF/CPF power-intent verification  \n'
'5. **Physical Design Agent** → floorplan, P&R, DRC/LVS  \n'
))

# ═══════════════════════════════════════════════════════════════════════════════
# Cell 4 — Dataclasses for messages + PPA (code)
# ═══════════════════════════════════════════════════════════════════════════════
cells.append(code(
'# ──────────────────────────────────────────────────────────────\n'
'#  Core data structures: messages and PPA metrics\n'
'# ──────────────────────────────────────────────────────────────\n'
'\n'
'@dataclass(frozen=True)\n'
'class PPAMetrics:\n'
'    """Power-Performance-Area figure of merit."""\n'
'\n'
'    power_mw: float\n'
'    performance_mhz: float\n'
'    area_um2: float\n'
'\n'
'    @property\n'
'    def ppa_score(self) -> float:\n'
'        """Lower is better: normalised product of power and area divided by performance."""\n'
'        return (self.power_mw * self.area_um2) / max(self.performance_mhz, 1e-9)\n'
'\n'
'    def __repr__(self) -> str:\n'
'        return (\n'
'            f"PPA(P={self.power_mw:.2f} mW, "\n'
'            f"f={self.performance_mhz:.0f} MHz, "\n'
'            f"A={self.area_um2:.0f} um2) "\n'
'            f"-> score={self.ppa_score:.2f}"\n'
'        )\n'
'\n'
'\n'
'class TaskStatus(enum.Enum):\n'
'    PENDING = "pending"\n'
'    RUNNING = "running"\n'
'    DONE = "done"\n'
'    FAILED = "failed"\n'
'\n'
'\n'
'@dataclass\n'
'class AgentTask:\n'
'    """A unit of work dispatched by the supervisor."""\n'
'\n'
'    task_id: str = field(default_factory=lambda: uuid.uuid4().hex[:8])\n'
'    description: str = ""\n'
'    assigned_to: str = ""\n'
'    status: TaskStatus = TaskStatus.PENDING\n'
'    result: Optional[str] = None\n'
'    ppa: Optional[PPAMetrics] = None\n'
'\n'
'\n'
'@dataclass\n'
'class TaskMessage:\n'
'    """Typed message exchanged between supervisor and workers."""\n'
'\n'
'    sender: str\n'
'    receiver: str\n'
'    payload: AgentTask\n'
'    timestamp: str = field(\n'
'        default_factory=lambda: datetime.now(timezone.utc).isoformat()\n'
'    )\n'
'\n'
'\n'
'print("Data structures defined: PPAMetrics, TaskStatus, AgentTask, TaskMessage")\n'
'sample = PPAMetrics(power_mw=1.2, performance_mhz=800, area_um2=45000)\n'
'print(f"  Example: {sample}")\n'
))

# ═══════════════════════════════════════════════════════════════════════════════
# Cell 5 — Supervisor + Worker classes (code)
# ═══════════════════════════════════════════════════════════════════════════════
cells.append(code(
'# ──────────────────────────────────────────────────────────────\n'
'#  SupervisorAgent  &  WorkerAgent\n'
'# ──────────────────────────────────────────────────────────────\n'
'\n'
'class WorkerAgent:\n'
'    """Specialist worker that executes a single sub-task."""\n'
'\n'
'    def __init__(self, name: str, specialty: str) -> None:\n'
'        self.name = name\n'
'        self.specialty = specialty\n'
'\n'
'    def execute(self, task: AgentTask) -> AgentTask:\n'
'        """Simulate task execution and return PPA metrics."""\n'
'        task.status = TaskStatus.RUNNING\n'
'        ppa = PPAMetrics(\n'
'            power_mw=round(random.uniform(0.5, 3.0), 2),\n'
'            performance_mhz=round(random.uniform(400, 1200)),\n'
'            area_um2=round(random.uniform(20000, 80000)),\n'
'        )\n'
'        task.ppa = ppa\n'
'        task.result = f"{self.specialty} completed: netlist optimised"\n'
'        task.status = TaskStatus.DONE\n'
'        return task\n'
'\n'
'\n'
'class SupervisorAgent:\n'
'    """Central orchestrator that decomposes intent and dispatches work."""\n'
'\n'
'    def __init__(self, name: str = "Supervisor") -> None:\n'
'        self.name = name\n'
'        self.workers: dict[str, WorkerAgent] = {}\n'
'        self.message_log: list[TaskMessage] = []\n'
'\n'
'    def register_worker(self, worker: WorkerAgent) -> None:\n'
'        self.workers[worker.name] = worker\n'
'\n'
'    def decompose(self, intent: str) -> list[AgentTask]:\n'
'        """Decompose high-level intent into sub-tasks (mock LLM call)."""\n'
'        sub_tasks_desc = [\n'
'            ("Synthesis", "Synthesise RTL to gate-level netlist"),\n'
'            ("DFT", "Insert scan chains and generate ATPG vectors"),\n'
'            ("STA", "Run static timing analysis across PVT corners"),\n'
'            ("Power", "Verify UPF power intent and estimate leakage"),\n'
'            ("PD", "Execute placement, routing, and physical verification"),\n'
'        ]\n'
'        tasks = []\n'
'        for worker_name, desc in sub_tasks_desc:\n'
'            t = AgentTask(description=desc, assigned_to=worker_name)\n'
'            tasks.append(t)\n'
'        return tasks\n'
'\n'
'    def dispatch_and_collect(self, intent: str) -> list[AgentTask]:\n'
'        """Full orchestration loop."""\n'
'        tasks = self.decompose(intent)\n'
'        completed: list[AgentTask] = []\n'
'        for task in tasks:\n'
'            worker = self.workers.get(task.assigned_to)\n'
'            if worker is None:\n'
'                task.status = TaskStatus.FAILED\n'
'                task.result = f"No worker registered for \'{task.assigned_to}\'"\n'
'                completed.append(task)\n'
'                continue\n'
'            msg_out = TaskMessage(sender=self.name, receiver=worker.name, payload=task)\n'
'            self.message_log.append(msg_out)\n'
'            result_task = worker.execute(task)\n'
'            msg_in = TaskMessage(sender=worker.name, receiver=self.name, payload=result_task)\n'
'            self.message_log.append(msg_in)\n'
'            completed.append(result_task)\n'
'        return completed\n'
'\n'
'\n'
'# ── Build and run ──\n'
'supervisor = SupervisorAgent()\n'
'for name, spec in [\n'
'    ("Synthesis", "Logic Synthesis"),\n'
'    ("DFT", "Design-for-Test"),\n'
'    ("STA", "Static Timing Analysis"),\n'
'    ("Power", "Power Analysis"),\n'
'    ("PD", "Physical Design"),\n'
']:\n'
'    supervisor.register_worker(WorkerAgent(name, spec))\n'
'\n'
'results = supervisor.dispatch_and_collect("Implement a low-power RISC-V core in 7 nm")\n'
'\n'
'print(f"{\'Worker\':<12} {\'Status\':<8} {\'PPA Score\':>10}  Description")\n'
'print("─" * 65)\n'
'for t in results:\n'
'    score = f"{t.ppa.ppa_score:.2f}" if t.ppa else "N/A"\n'
'    print(f"{t.assigned_to:<12} {t.status.value:<8} {score:>10}  {t.description}")\n'
'print(f"\\nTotal messages exchanged: {len(supervisor.message_log)}")\n'
))

# ═══════════════════════════════════════════════════════════════════════════════
# Cell 6 — Supervisor-Worker Topology Viz (code)
# ═══════════════════════════════════════════════════════════════════════════════
cells.append(code(
'# ──────────────────────────────────────────────────────────────\n'
'#  Visualisation: Supervisor-Worker topology (networkx)\n'
'# ──────────────────────────────────────────────────────────────\n'
'\n'
'fig, ax = plt.subplots(figsize=(10, 7))\n'
'\n'
'G = nx.DiGraph()\n'
'G.add_node("Supervisor", role="supervisor")\n'
'workers = ["Synthesis", "DFT", "STA", "Power", "PD"]\n'
'for w in workers:\n'
'    G.add_node(w, role="worker")\n'
'    G.add_edge("Supervisor", w, label="dispatch")\n'
'    G.add_edge(w, "Supervisor", label="result")\n'
'\n'
'pos = nx.shell_layout(G, nlist=[["Supervisor"], workers])\n'
'colours = [\n'
'    "#FF6B6B" if G.nodes[n]["role"] == "supervisor" else "#4ECDC4"\n'
'    for n in G.nodes()\n'
']\n'
'sizes = [3000 if G.nodes[n]["role"] == "supervisor" else 2000 for n in G.nodes()]\n'
'\n'
'nx.draw_networkx_nodes(G, pos, node_color=colours, node_size=sizes, ax=ax)\n'
'nx.draw_networkx_labels(G, pos, font_size=10, font_weight="bold", ax=ax)\n'
'nx.draw_networkx_edges(\n'
'    G, pos, edge_color="#888", arrows=True,\n'
'    arrowsize=20, connectionstyle="arc3,rad=0.1", ax=ax,\n'
')\n'
'\n'
'legend_elements = [\n'
'    mpatches.Patch(facecolor="#FF6B6B", label="Supervisor (Orchestrator)"),\n'
'    mpatches.Patch(facecolor="#4ECDC4", label="Worker (Specialist)"),\n'
']\n'
'ax.legend(handles=legend_elements, loc="upper left", fontsize=10)\n'
'ax.set_title(\n'
'    "Pattern 1 — Supervisor-Worker Topology", fontsize=14, fontweight="bold"\n'
')\n'
'ax.axis("off")\n'
'plt.tight_layout()\n'
'plt.show()\n'
))

# ═══════════════════════════════════════════════════════════════════════════════
# Cell 7 — Section 2.3 intro (markdown)
# ═══════════════════════════════════════════════════════════════════════════════
cells.append(md(
'---\n'
'\n'
'## 2.3 Pattern 2 — Consensus-Based Reasoning\n'
'\n'
'### Concept\n'
'\n'
'Instead of a single agent making unilateral design decisions, **multiple\n'
'divergent-thought agents** independently propose candidate solutions.\n'
'An **Arbiter Agent** then evaluates all proposals against quantitative\n'
'criteria and selects the optimum.\n'
'\n'
'This mirrors the *brainstorming → evaluation* cycle used by experienced\n'
'design teams and is especially valuable when the solution space is\n'
'non-convex (as it almost always is in analog circuit topology selection).\n'
'\n'
'### Mathematical Formulation\n'
'\n'
'Given $k$ proposals $\\{P_1, \\ldots, P_k\\}$, each characterised by a\n'
'PPA vector $\\mathbf{v}_i = (p_i,\\, f_i,\\, a_i)$, the arbiter computes a\n'
'**weighted objective**:\n'
'\n'
'$$\n'
'J(P_i) \\;=\\; \\alpha \\cdot \\hat{p}_i \\;+\\; \\beta \\cdot (1 - \\hat{f}_i) \\;+\\; \\gamma \\cdot \\hat{a}_i\n'
'$$\n'
'\n'
'where $\\hat{x}$ denotes min-max normalisation across proposals and\n'
'$\\alpha + \\beta + \\gamma = 1$ are user-specified weights (lower $J$ is better).\n'
'\n'
'The winning proposal is:\n'
'\n'
'$$\n'
'P^* = \\arg\\min_{i \\in \\{1,\\ldots,k\\}} J(P_i)\n'
'$$\n'
'\n'
'> **Analogy:** This is analogous to **multi-objective optimisation** with\n'
'> scalarisation — a well-studied approach in the analog sizing literature\n'
'> (Gielen & Rutenbar, 2000).\n'
))

# ═══════════════════════════════════════════════════════════════════════════════
# Cell 8 — Consensus implementation (code)
# ═══════════════════════════════════════════════════════════════════════════════
cells.append(code(
'# ──────────────────────────────────────────────────────────────\n'
'#  Consensus-Based Reasoning: dataclasses & agents\n'
'# ──────────────────────────────────────────────────────────────\n'
'\n'
'@dataclass\n'
'class TopologyProposal:\n'
'    """A candidate circuit topology with PPA estimates."""\n'
'\n'
'    proposal_id: str = field(default_factory=lambda: uuid.uuid4().hex[:6])\n'
'    topology_name: str = ""\n'
'    description: str = ""\n'
'    ppa: PPAMetrics = field(default_factory=lambda: PPAMetrics(0, 0, 0))\n'
'    rationale: str = ""\n'
'\n'
'\n'
'class ProposalAgent:\n'
'    """Generates a single design proposal (simulates an LLM-backed agent)."""\n'
'\n'
'    def __init__(self, name: str, style: str) -> None:\n'
'        self.name = name\n'
'        self.style = style\n'
'\n'
'    def propose(self, spec: str) -> TopologyProposal:\n'
'        styles = {\n'
'            "low-power": PPAMetrics(\n'
'                power_mw=round(random.uniform(0.3, 0.8), 2),\n'
'                performance_mhz=round(random.uniform(300, 600)),\n'
'                area_um2=round(random.uniform(40000, 70000)),\n'
'            ),\n'
'            "high-speed": PPAMetrics(\n'
'                power_mw=round(random.uniform(1.5, 3.0), 2),\n'
'                performance_mhz=round(random.uniform(900, 1400)),\n'
'                area_um2=round(random.uniform(50000, 90000)),\n'
'            ),\n'
'            "area-efficient": PPAMetrics(\n'
'                power_mw=round(random.uniform(0.8, 1.5), 2),\n'
'                performance_mhz=round(random.uniform(500, 800)),\n'
'                area_um2=round(random.uniform(15000, 35000)),\n'
'            ),\n'
'            "balanced": PPAMetrics(\n'
'                power_mw=round(random.uniform(0.6, 1.2), 2),\n'
'                performance_mhz=round(random.uniform(600, 900)),\n'
'                area_um2=round(random.uniform(30000, 55000)),\n'
'            ),\n'
'        }\n'
'        ppa = styles.get(self.style, styles["balanced"])\n'
'        return TopologyProposal(\n'
'            topology_name=f"{self.style.title()} Topology",\n'
'            description=f"Optimised for {self.style}: {spec}",\n'
'            ppa=ppa,\n'
'            rationale=f"Agent {self.name} prioritises {self.style} metrics.",\n'
'        )\n'
'\n'
'\n'
'class ArbiterAgent:\n'
'    """Evaluates proposals using a weighted PPA objective."""\n'
'\n'
'    def __init__(\n'
'        self, alpha: float = 0.4, beta: float = 0.3, gamma: float = 0.3\n'
'    ) -> None:\n'
'        self.alpha = alpha\n'
'        self.beta = beta\n'
'        self.gamma = gamma\n'
'\n'
'    def _normalise(self, values: list[float]) -> list[float]:\n'
'        lo, hi = min(values), max(values)\n'
'        if hi - lo < 1e-12:\n'
'            return [0.5] * len(values)\n'
'        return [(v - lo) / (hi - lo) for v in values]\n'
'\n'
'    def evaluate(\n'
'        self, proposals: list[TopologyProposal]\n'
'    ) -> tuple[TopologyProposal, list[float]]:\n'
'        powers = [p.ppa.power_mw for p in proposals]\n'
'        freqs = [p.ppa.performance_mhz for p in proposals]\n'
'        areas = [p.ppa.area_um2 for p in proposals]\n'
'\n'
'        p_norm = self._normalise(powers)\n'
'        f_norm = self._normalise(freqs)\n'
'        a_norm = self._normalise(areas)\n'
'\n'
'        scores = []\n'
'        for i in range(len(proposals)):\n'
'            j = (\n'
'                self.alpha * p_norm[i]\n'
'                + self.beta * (1 - f_norm[i])\n'
'                + self.gamma * a_norm[i]\n'
'            )\n'
'            scores.append(round(j, 4))\n'
'\n'
'        best_idx = int(np.argmin(scores))\n'
'        return proposals[best_idx], scores\n'
'\n'
'\n'
'# ── Run consensus ──\n'
'proposal_agents = [\n'
'    ProposalAgent("Agent-alpha", "low-power"),\n'
'    ProposalAgent("Agent-beta", "high-speed"),\n'
'    ProposalAgent("Agent-gamma", "area-efficient"),\n'
'    ProposalAgent("Agent-delta", "balanced"),\n'
']\n'
'\n'
'spec_text = "Folded-cascode OTA, GBW >= 100 MHz, CL = 2 pF"\n'
'proposals = [a.propose(spec_text) for a in proposal_agents]\n'
'\n'
'arbiter = ArbiterAgent(alpha=0.4, beta=0.3, gamma=0.3)\n'
'winner, scores = arbiter.evaluate(proposals)\n'
'\n'
'print(f"{\'Proposal\':<28} {\'Power\':>8} {\'Freq\':>8} {\'Area\':>8} {\'Score\':>8}")\n'
'print("─" * 68)\n'
'for p, s in zip(proposals, scores):\n'
'    tag = " *" if p.proposal_id == winner.proposal_id else ""\n'
'    print(\n'
'        f"{p.topology_name:<28} {p.ppa.power_mw:>7.2f}  "\n'
'        f"{p.ppa.performance_mhz:>7.0f}  "\n'
'        f"{p.ppa.area_um2:>7.0f}  {s:>7.4f}{tag}"\n'
'    )\n'
'print(f"\\nArbiter selects: {winner.topology_name} (score = {min(scores):.4f})")\n'
))

# ═══════════════════════════════════════════════════════════════════════════════
# Cell 9 — Radar chart (code)
# ═══════════════════════════════════════════════════════════════════════════════
cells.append(code(
'# ──────────────────────────────────────────────────────────────\n'
'#  Interactive radar chart: PPA comparison (Plotly)\n'
'# ──────────────────────────────────────────────────────────────\n'
'\n'
'categories = ["Power (mW)", "Frequency (MHz/100)", "Area (um2/10k)"]\n'
'\n'
'fig = go.Figure()\n'
'\n'
'for prop, score in zip(proposals, scores):\n'
'    vals = [\n'
'        prop.ppa.power_mw,\n'
'        prop.ppa.performance_mhz / 100,\n'
'        prop.ppa.area_um2 / 10000,\n'
'    ]\n'
'    vals.append(vals[0])  # close the polygon\n'
'    cats = categories + [categories[0]]\n'
'    fig.add_trace(\n'
'        go.Scatterpolar(\n'
'            r=vals,\n'
'            theta=cats,\n'
'            fill="toself",\n'
'            name=f"{prop.topology_name} (J={score:.3f})",\n'
'        )\n'
'    )\n'
'\n'
'fig.update_layout(\n'
'    polar=dict(radialaxis=dict(visible=True, range=[0, 10])),\n'
'    title="Consensus-Based Reasoning — PPA Radar Comparison",\n'
'    showlegend=True,\n'
'    template="plotly_white",\n'
'    width=750,\n'
'    height=550,\n'
')\n'
'fig.show()\n'
))

# ═══════════════════════════════════════════════════════════════════════════════
# Cell 10 — Section 2.4 Handoff intro (markdown)
# ═══════════════════════════════════════════════════════════════════════════════
cells.append(md(
'---\n'
'\n'
'## 2.4 Pattern 3 — Handoff Pattern\n'
'\n'
'### Concept\n'
'\n'
'In many analog design flows, failure in one stage does not terminate the\n'
'pipeline — it **redirects** control to an earlier (or alternative) stage\n'
'with rich **error context**.\n'
'\n'
'> **Example:** The Sizing Agent fails to meet a gain target of 60 dB.\n'
'> Rather than crashing, it *hands back* control to the Topology Selection\n'
'> Agent with a structured error report:\n'
'>\n'
'> ```python\n'
'> HandoffContext(\n'
'>     source="SizingAgent",\n'
'>     target="TopologyAgent",\n'
'>     reason="gain_violation",\n'
'>     data={"achieved_gain_db": 52.3, "target_gain_db": 60.0},\n'
'> )\n'
'> ```\n'
'>\n'
'> The Topology Agent can then select a higher-gain topology (e.g.,\n'
'> regulated cascode instead of simple cascode) and re-enter the sizing\n'
'> phase.\n'
'\n'
'### Formal Definition\n'
'\n'
'A **handoff** is a triple $h = (s, t, c)$ where:\n'
'\n'
'- $s \\in \\mathcal{A}$ is the **source** agent\n'
'- $t \\in \\mathcal{A}$ is the **target** agent (may differ from the predecessor)\n'
'- $c$ is a **context object** carrying partial results and error diagnostics\n'
'\n'
'The set of valid handoffs defines a **state machine** over the agent pool.\n'
'\n'
'The **convergence guarantee** relies on monotonic progress:\n'
'\n'
'$$\n'
'\\forall\\, h_i = (s, t, c_i): \\quad \\|c_{i+1}\\|_{\\text{info}} > \\|c_i\\|_{\\text{info}}\n'
'$$\n'
'\n'
'i.e., each handoff must carry strictly more information than the previous one,\n'
'preventing infinite loops over the same failure mode.\n'
))

# ═══════════════════════════════════════════════════════════════════════════════
# Cell 11 — Handoff implementation (code)
# ═══════════════════════════════════════════════════════════════════════════════
cells.append(code(
'# ──────────────────────────────────────────────────────────────\n'
'#  Handoff Pattern: protocol and specialist agents\n'
'# ──────────────────────────────────────────────────────────────\n'
'\n'
'@dataclass\n'
'class HandoffContext:\n'
'    """Structured context transferred during a handoff."""\n'
'\n'
'    source: str\n'
'    target: str\n'
'    reason: str\n'
'    data: dict[str, Any] = field(default_factory=dict)\n'
'    iteration: int = 0\n'
'\n'
'\n'
'class SpecialistAgent(ABC):\n'
'    """Base class for agents that participate in handoff chains."""\n'
'\n'
'    def __init__(self, name: str) -> None:\n'
'        self.name = name\n'
'\n'
'    @abstractmethod\n'
'    def run(self, context: dict[str, Any]) -> tuple[bool, dict[str, Any]]:\n'
'        """Execute the agent task. Returns (success, updated_context)."""\n'
'        ...\n'
'\n'
'\n'
'class TopologyAgent(SpecialistAgent):\n'
'    def run(self, context: dict[str, Any]) -> tuple[bool, dict[str, Any]]:\n'
'        iteration = context.get("iteration", 0)\n'
'        topologies = ["simple_cascode", "folded_cascode", "regulated_cascode"]\n'
'        chosen = topologies[min(iteration, len(topologies) - 1)]\n'
'        context["topology"] = chosen\n'
'        context["max_gain_potential_db"] = {\n'
'            "simple_cascode": 55,\n'
'            "folded_cascode": 65,\n'
'            "regulated_cascode": 80,\n'
'        }[chosen]\n'
'        print(\n'
'            f"  [TopologyAgent] Selected: {chosen} "\n'
'            f"(gain potential <= {context[\'max_gain_potential_db\']} dB)"\n'
'        )\n'
'        return True, context\n'
'\n'
'\n'
'class SizingAgent(SpecialistAgent):\n'
'    def run(self, context: dict[str, Any]) -> tuple[bool, dict[str, Any]]:\n'
'        target = context.get("target_gain_db", 60)\n'
'        potential = context.get("max_gain_potential_db", 50)\n'
'        achieved = round(potential * random.uniform(0.85, 0.99), 1)\n'
'        context["achieved_gain_db"] = achieved\n'
'        success = achieved >= target\n'
'        status = "MET" if success else "VIOLATED"\n'
'        print(\n'
'            f"  [SizingAgent] Achieved gain = {achieved:.1f} dB "\n'
'            f"(target = {target} dB) -> {status}"\n'
'        )\n'
'        return success, context\n'
'\n'
'\n'
'class SimulationAgentV2(SpecialistAgent):\n'
'    def run(self, context: dict[str, Any]) -> tuple[bool, dict[str, Any]]:\n'
'        gain = context.get("achieved_gain_db", 0)\n'
'        context["sim_verified"] = True\n'
'        print(f"  [SimAgent] SPICE verification passed (gain = {gain:.1f} dB)")\n'
'        return True, context\n'
'\n'
'\n'
'class HandoffProtocol:\n'
'    """Orchestrates handoff-driven control flow between specialists."""\n'
'\n'
'    def __init__(self, max_iterations: int = 5) -> None:\n'
'        self.max_iterations = max_iterations\n'
'        self.agents: dict[str, SpecialistAgent] = {}\n'
'        self.handoff_log: list[HandoffContext] = []\n'
'\n'
'    def register(self, agent: SpecialistAgent) -> None:\n'
'        self.agents[agent.name] = agent\n'
'\n'
'    def run_pipeline(self, initial_context: dict[str, Any]) -> dict[str, Any]:\n'
'        """Execute the handoff pipeline with retry semantics."""\n'
'        ctx = {**initial_context, "iteration": 0}\n'
'\n'
'        for i in range(self.max_iterations):\n'
'            ctx["iteration"] = i\n'
'            print(f"\\n-- Iteration {i} --")\n'
'\n'
'            ok, ctx = self.agents["topology"].run(ctx)\n'
'\n'
'            ok, ctx = self.agents["sizing"].run(ctx)\n'
'            if not ok:\n'
'                hc = HandoffContext(\n'
'                    source="sizing",\n'
'                    target="topology",\n'
'                    reason="gain_violation",\n'
'                    data={\n'
'                        "achieved": ctx["achieved_gain_db"],\n'
'                        "target": ctx["target_gain_db"],\n'
'                    },\n'
'                    iteration=i,\n'
'                )\n'
'                self.handoff_log.append(hc)\n'
'                print(f"  Handoff: sizing -> topology (reason: {hc.reason})")\n'
'                continue\n'
'\n'
'            ok, ctx = self.agents["simulation"].run(ctx)\n'
'            if ok:\n'
'                print(f"\\nDesign converged in {i + 1} iteration(s).")\n'
'                ctx["converged"] = True\n'
'                return ctx\n'
'\n'
'        ctx["converged"] = False\n'
'        print(f"\\nDid not converge within {self.max_iterations} iterations.")\n'
'        return ctx\n'
'\n'
'\n'
'# ── Run handoff demo ──\n'
'protocol = HandoffProtocol(max_iterations=5)\n'
'protocol.register(TopologyAgent("topology"))\n'
'protocol.register(SizingAgent("sizing"))\n'
'protocol.register(SimulationAgentV2("simulation"))\n'
'\n'
'result_ctx = protocol.run_pipeline({"target_gain_db": 60})\n'
'print(f"\\nHandoffs recorded: {len(protocol.handoff_log)}")\n'
))

# ═══════════════════════════════════════════════════════════════════════════════
# Cell 12 — State machine diagram (code)
# ═══════════════════════════════════════════════════════════════════════════════
cells.append(code(
'# ──────────────────────────────────────────────────────────────\n'
'#  Visualisation: Handoff state machine (networkx)\n'
'# ──────────────────────────────────────────────────────────────\n'
'\n'
'fig, ax = plt.subplots(figsize=(12, 6))\n'
'\n'
'SM = nx.DiGraph()\n'
'states = [\n'
'    "Spec Input",\n'
'    "Topology\\nSelection",\n'
'    "Sizing",\n'
'    "Simulation",\n'
'    "Design\\nClosure",\n'
']\n'
'for s in states:\n'
'    SM.add_node(s)\n'
'\n'
'SM.add_edge("Spec Input", "Topology\\nSelection", label="start")\n'
'SM.add_edge("Topology\\nSelection", "Sizing", label="topology_chosen")\n'
'SM.add_edge("Sizing", "Simulation", label="constraints_met")\n'
'SM.add_edge("Sizing", "Topology\\nSelection", label="gain_violation")\n'
'SM.add_edge("Simulation", "Design\\nClosure", label="pass")\n'
'SM.add_edge("Simulation", "Sizing", label="sim_fail")\n'
'\n'
'pos = {\n'
'    "Spec Input": (0, 0),\n'
'    "Topology\\nSelection": (2, 0),\n'
'    "Sizing": (4, 0),\n'
'    "Simulation": (6, 0),\n'
'    "Design\\nClosure": (8, 0),\n'
'}\n'
'\n'
'node_colors = ["#FFE66D", "#4ECDC4", "#4ECDC4", "#FF6B6B", "#A8E6CF"]\n'
'nx.draw_networkx_nodes(\n'
'    SM, pos, node_color=node_colors, node_size=2800, node_shape="s", ax=ax\n'
')\n'
'nx.draw_networkx_labels(SM, pos, font_size=8, font_weight="bold", ax=ax)\n'
'\n'
'forward_edges = [\n'
'    ("Spec Input", "Topology\\nSelection"),\n'
'    ("Topology\\nSelection", "Sizing"),\n'
'    ("Sizing", "Simulation"),\n'
'    ("Simulation", "Design\\nClosure"),\n'
']\n'
'back_edges = [\n'
'    ("Sizing", "Topology\\nSelection"),\n'
'    ("Simulation", "Sizing"),\n'
']\n'
'\n'
'nx.draw_networkx_edges(\n'
'    SM, pos, edgelist=forward_edges, edge_color="#2C3E50",\n'
'    arrows=True, arrowsize=20, ax=ax,\n'
')\n'
'nx.draw_networkx_edges(\n'
'    SM, pos, edgelist=back_edges, edge_color="#E74C3C",\n'
'    arrows=True, arrowsize=20,\n'
'    connectionstyle="arc3,rad=0.3", style="dashed", ax=ax,\n'
')\n'
'\n'
'edge_labels = nx.get_edge_attributes(SM, "label")\n'
'nx.draw_networkx_edge_labels(SM, pos, edge_labels=edge_labels, font_size=7, ax=ax)\n'
'\n'
'ax.set_title(\n'
'    "Pattern 3 — Handoff State Machine", fontsize=14, fontweight="bold"\n'
')\n'
'ax.axis("off")\n'
'plt.tight_layout()\n'
'plt.show()\n'
))

# ═══════════════════════════════════════════════════════════════════════════════
# Cell 13 — Section 2.5 DAG intro (markdown)
# ═══════════════════════════════════════════════════════════════════════════════
cells.append(md(
'---\n'
'\n'
'## 2.5 Pattern 4 — Stateful Graph Workflows (DAGs and Cycles)\n'
'\n'
'### Concept\n'
'\n'
'The most general pattern represents the design flow as a **directed graph**\n'
'where each node is an agent (or agent group) and each edge encodes a data\n'
'dependency or control-flow transition.\n'
'\n'
'- **DAG (Directed Acyclic Graph):** Used when the flow is feed-forward\n'
'  (e.g., spec → topology → sizing → layout).\n'
'- **Cyclic Graph:** Used when iterative refinement is needed (simulation\n'
'  fail → loop back to sizing or topology).\n'
'\n'
'> **Key Insight:** Frameworks such as **LangGraph** (Chapter 3) formalise\n'
'> this pattern with first-class support for state, conditional edges, and\n'
'> human-in-the-loop checkpoints.\n'
'\n'
'### Graph-Theoretic View\n'
'\n'
'Let $G = (V, E)$ where:\n'
'\n'
'- $V = \\{v_1, \\ldots, v_n\\}$ — the set of agent nodes  \n'
'- $E \\subseteq V \\times V$ — directed edges representing data/control flow\n'
'\n'
'A **topological ordering** $\\sigma$ of a DAG determines a valid execution\n'
'schedule.  When $G$ contains cycles, we introduce a **convergence\n'
'predicate** $\\phi(s)$ on the shared state $s$ that terminates iteration:\n'
'\n'
'$$\n'
'\\text{while } \\lnot\\,\\phi(s): \\quad s \\leftarrow \\text{execute\\_cycle}(G, s)\n'
'$$\n'
'\n'
'For the analog design domain the convergence predicate typically checks\n'
'whether all PPA constraints are satisfied:\n'
'\n'
'$$\n'
'\\phi(s) = \\bigwedge_{c \\in \\mathcal{C}} \\left[ s_c \\geq \\text{target}_c \\right]\n'
'$$\n'
))

# ═══════════════════════════════════════════════════════════════════════════════
# Cell 14 — DAG implementation (code)
# ═══════════════════════════════════════════════════════════════════════════════
cells.append(code(
'# ──────────────────────────────────────────────────────────────\n'
'#  Stateful Graph Workflow: DAG with conditional back-edges\n'
'# ──────────────────────────────────────────────────────────────\n'
'\n'
'class GraphNode:\n'
'    """A node in the design-flow graph."""\n'
'\n'
'    def __init__(\n'
'        self,\n'
'        name: str,\n'
'        agent_type: str,\n'
'        func: Callable[[dict], tuple[str, dict]],\n'
'    ) -> None:\n'
'        self.name = name\n'
'        self.agent_type = agent_type\n'
'        self.func = func\n'
'\n'
'    def execute(self, state: dict[str, Any]) -> tuple[str, dict[str, Any]]:\n'
'        return self.func(state)\n'
'\n'
'\n'
'class DesignFlowGraph:\n'
'    """Executable directed graph of agent nodes."""\n'
'\n'
'    def __init__(self) -> None:\n'
'        self.nodes: dict[str, GraphNode] = {}\n'
'        self.edges: dict[str, dict[str, str]] = {}\n'
'\n'
'    def add_node(self, node: GraphNode) -> None:\n'
'        self.nodes[node.name] = node\n'
'\n'
'    def add_edge(\n'
'        self, source: str, target: str, condition: str = "default"\n'
'    ) -> None:\n'
'        self.edges.setdefault(source, {})[condition] = target\n'
'\n'
'    def run(\n'
'        self, entry: str, state: dict[str, Any], max_steps: int = 20\n'
'    ) -> dict[str, Any]:\n'
'        current = entry\n'
'        for step in range(max_steps):\n'
'            node = self.nodes[current]\n'
'            outcome, state = node.execute(state)\n'
'            state.setdefault("trace", []).append((current, outcome))\n'
'            print(f"  Step {step}: {current} -> outcome=\'{outcome}\'")\n'
'\n'
'            transitions = self.edges.get(current, {})\n'
'            next_node = transitions.get(outcome, transitions.get("default"))\n'
'            if next_node is None:\n'
'                print(f"  Terminal node reached: {current}")\n'
'                break\n'
'            current = next_node\n'
'\n'
'        return state\n'
'\n'
'\n'
'# ── Build the analog design DAG ──\n'
'\n'
'def spec_input_fn(s: dict) -> tuple[str, dict]:\n'
'    s["spec"] = {"GBW_MHz": 100, "CL_pF": 2, "gain_dB": 60}\n'
'    return "default", s\n'
'\n'
'\n'
'def topology_select_fn(s: dict) -> tuple[str, dict]:\n'
'    iteration = s.get("topo_iter", 0)\n'
'    topos = ["telescopic", "folded_cascode", "two_stage_miller"]\n'
'    s["topology"] = topos[min(iteration, len(topos) - 1)]\n'
'    s["topo_iter"] = iteration + 1\n'
'    return "default", s\n'
'\n'
'\n'
'def sizing_fn(s: dict) -> tuple[str, dict]:\n'
'    s["sizes"] = {\n'
'        "W1": round(random.uniform(5, 50), 1),\n'
'        "L1": 0.18,\n'
'        "Id": round(random.uniform(50, 200)),\n'
'    }\n'
'    return "default", s\n'
'\n'
'\n'
'def simulation_fn(s: dict) -> tuple[str, dict]:\n'
'    target = s["spec"]["gain_dB"]\n'
'    achieved = round(random.uniform(0.8, 1.1) * target, 1)\n'
'    s["sim_gain_dB"] = achieved\n'
'    return ("pass" if achieved >= target else "fail"), s\n'
'\n'
'\n'
'def layout_fn(s: dict) -> tuple[str, dict]:\n'
'    s["layout_done"] = True\n'
'    return "default", s\n'
'\n'
'\n'
'def closure_fn(s: dict) -> tuple[str, dict]:\n'
'    s["design_closed"] = True\n'
'    return "terminal", s\n'
'\n'
'\n'
'flow = DesignFlowGraph()\n'
'flow.add_node(GraphNode("Spec", "input", spec_input_fn))\n'
'flow.add_node(GraphNode("Topology", "agent", topology_select_fn))\n'
'flow.add_node(GraphNode("Sizing", "agent", sizing_fn))\n'
'flow.add_node(GraphNode("Simulation", "oracle", simulation_fn))\n'
'flow.add_node(GraphNode("Layout", "agent", layout_fn))\n'
'flow.add_node(GraphNode("Closure", "terminal", closure_fn))\n'
'\n'
'flow.add_edge("Spec", "Topology")\n'
'flow.add_edge("Topology", "Sizing")\n'
'flow.add_edge("Sizing", "Simulation")\n'
'flow.add_edge("Simulation", "Layout", condition="pass")\n'
'flow.add_edge("Simulation", "Topology", condition="fail")\n'
'flow.add_edge("Layout", "Closure")\n'
'\n'
'print("Running analog design DAG...\\n")\n'
'final_state = flow.run("Spec", {})\n'
'print(f"\\nFinal topology: {final_state.get(\'topology\')}")\n'
'print(f"Simulated gain:  {final_state.get(\'sim_gain_dB\')} dB")\n'
'print(f"Design closed:   {final_state.get(\'design_closed\', False)}")\n'
))

# ═══════════════════════════════════════════════════════════════════════════════
# Cell 15 — DAG Visualisation (code)
# ═══════════════════════════════════════════════════════════════════════════════
cells.append(code(
'# ──────────────────────────────────────────────────────────────\n'
'#  Visualisation: Analog design flow DAG (networkx)\n'
'# ──────────────────────────────────────────────────────────────\n'
'\n'
'fig, ax = plt.subplots(figsize=(13, 7))\n'
'\n'
'DAG = nx.DiGraph()\n'
'node_info = {\n'
'    "Spec Input": ("input", "#FFE66D"),\n'
'    "Supervisor\\nAgent": ("supervisor", "#FF6B6B"),\n'
'    "Topology\\nAgent": ("agent", "#4ECDC4"),\n'
'    "Sizing\\nAgent": ("agent", "#4ECDC4"),\n'
'    "Simulation\\nAgent": ("oracle", "#45B7D1"),\n'
'    "Physical\\nLayout Agent": ("agent", "#4ECDC4"),\n'
'    "Design\\nClosure": ("terminal", "#A8E6CF"),\n'
'}\n'
'\n'
'for name, (role, color) in node_info.items():\n'
'    DAG.add_node(name, role=role, color=color)\n'
'\n'
'DAG.add_edge("Spec Input", "Supervisor\\nAgent")\n'
'DAG.add_edge("Supervisor\\nAgent", "Topology\\nAgent")\n'
'DAG.add_edge("Supervisor\\nAgent", "Sizing\\nAgent")\n'
'DAG.add_edge("Topology\\nAgent", "Simulation\\nAgent")\n'
'DAG.add_edge("Sizing\\nAgent", "Simulation\\nAgent")\n'
'DAG.add_edge("Simulation\\nAgent", "Physical\\nLayout Agent", label="Pass")\n'
'DAG.add_edge("Simulation\\nAgent", "Supervisor\\nAgent", label="Fail")\n'
'DAG.add_edge("Physical\\nLayout Agent", "Design\\nClosure")\n'
'\n'
'pos = {\n'
'    "Spec Input": (0, 2),\n'
'    "Supervisor\\nAgent": (2, 2),\n'
'    "Topology\\nAgent": (4, 3),\n'
'    "Sizing\\nAgent": (4, 1),\n'
'    "Simulation\\nAgent": (6, 2),\n'
'    "Physical\\nLayout Agent": (8, 2),\n'
'    "Design\\nClosure": (10, 2),\n'
'}\n'
'\n'
'colors = [node_info[n][1] for n in DAG.nodes()]\n'
'\n'
'nx.draw_networkx_nodes(\n'
'    DAG, pos, node_color=colors, node_size=3000,\n'
'    node_shape="o", ax=ax, edgecolors="#333", linewidths=1.5,\n'
')\n'
'nx.draw_networkx_labels(DAG, pos, font_size=8, font_weight="bold", ax=ax)\n'
'\n'
'forward = [\n'
'    (u, v) for u, v, d in DAG.edges(data=True) if d.get("label") != "Fail"\n'
']\n'
'back = [\n'
'    (u, v) for u, v, d in DAG.edges(data=True) if d.get("label") == "Fail"\n'
']\n'
'\n'
'nx.draw_networkx_edges(\n'
'    DAG, pos, edgelist=forward, edge_color="#2C3E50",\n'
'    arrows=True, arrowsize=25, ax=ax, width=2,\n'
')\n'
'nx.draw_networkx_edges(\n'
'    DAG, pos, edgelist=back, edge_color="#E74C3C",\n'
'    arrows=True, arrowsize=25, style="dashed",\n'
'    connectionstyle="arc3,rad=0.3", ax=ax, width=2,\n'
')\n'
'\n'
'edge_labels = {\n'
'    (u, v): d["label"] for u, v, d in DAG.edges(data=True) if "label" in d\n'
'}\n'
'nx.draw_networkx_edge_labels(\n'
'    DAG, pos, edge_labels=edge_labels, font_size=9,\n'
'    font_color="#C0392B", ax=ax,\n'
')\n'
'\n'
'legend_elems = [\n'
'    mpatches.Patch(facecolor="#FFE66D", edgecolor="#333", label="Input"),\n'
'    mpatches.Patch(facecolor="#FF6B6B", edgecolor="#333", label="Supervisor"),\n'
'    mpatches.Patch(facecolor="#4ECDC4", edgecolor="#333", label="Specialist Agent"),\n'
'    mpatches.Patch(facecolor="#45B7D1", edgecolor="#333", label="Simulation Oracle"),\n'
'    mpatches.Patch(facecolor="#A8E6CF", edgecolor="#333", label="Terminal"),\n'
']\n'
'ax.legend(handles=legend_elems, loc="lower left", fontsize=9)\n'
'ax.set_title(\n'
'    "Pattern 4 — Stateful Graph Workflow: Analog Design DAG",\n'
'    fontsize=14, fontweight="bold",\n'
')\n'
'ax.axis("off")\n'
'plt.tight_layout()\n'
'plt.show()\n'
))

# ═══════════════════════════════════════════════════════════════════════════════
# Cell 16 — Mermaid diagram (markdown)
# ═══════════════════════════════════════════════════════════════════════════════
cells.append(md(
'### Mermaid Representation\n'
'\n'
'The same graph expressed as a Mermaid diagram (renderable in GitHub, Jupyter,\n'
'and most documentation systems):\n'
'\n'
'```mermaid\n'
'graph TD\n'
'    A[Spec Input] --> B{Supervisor Agent}\n'
'    B --> C[Topology Agent]\n'
'    B --> D[Sizing Agent]\n'
'    C --> E[Simulation Agent]\n'
'    D --> E\n'
'    E -- Pass --> F[Physical Layout Agent]\n'
'    E -- Fail --> B\n'
'    F --> G[Design Closure]\n'
'```\n'
'\n'
'> **Note:** Mermaid diagrams provide a lightweight, version-controllable\n'
'> representation of agent topologies that can be embedded in design\n'
'> documentation and CI/CD dashboards.\n'
))

# ═══════════════════════════════════════════════════════════════════════════════
# Cell 17 — Section 2.6 Hybrid intro (markdown)
# ═══════════════════════════════════════════════════════════════════════════════
cells.append(md(
'---\n'
'\n'
'## 2.6 Hybrid Architectures: Combining Patterns\n'
'\n'
'### Real-World Observation\n'
'\n'
'Production EDA systems rarely use a single pattern in isolation.  Instead,\n'
'they **compose** patterns hierarchically:\n'
'\n'
'| Layer | Pattern | Example |\n'
'|-------|---------|--------|\n'
'| **Outer** | Supervisor-Worker | A top-level orchestrator dispatches to domain groups |\n'
'| **Middle** | Consensus | Each domain group uses 3 proposal agents + 1 arbiter |\n'
'| **Inner** | Handoff | Within a proposal agent, sizing <-> simulation loops |\n'
'| **Foundation** | Stateful Graph | The entire flow is a DAG with conditional back-edges |\n'
'\n'
'### When to Use Which Pattern\n'
'\n'
'| Criterion | Supervisor | Consensus | Handoff | Graph |\n'
'|-----------|-----------|-----------|---------|-------|\n'
'| Complexity of decision | Low | High | Medium | Any |\n'
'| Need for diversity of thought | Low | **Critical** | Low | Varies |\n'
'| Iterative refinement | No | No | **Yes** | **Yes** |\n'
'| Parallelism | High | High | Low | Depends on DAG |\n'
'| Auditability | High | Medium | High | **Highest** |\n'
'| Implementation effort | Low | Medium | Medium | High |\n'
'\n'
'> **Design Heuristic:** Start with the simplest pattern that satisfies your\n'
'> auditability and convergence requirements.  Add complexity only when\n'
'> empirical evidence (e.g., design-quality regressions) justifies it.\n'
'\n'
'### Composition Rules\n'
'\n'
'Let $\\mathcal{P} = \\{\\text{Sup}, \\text{Con}, \\text{Hand}, \\text{Graph}\\}$ be the set of patterns.\n'
'A hybrid architecture $H$ is a partial order over pattern instances:\n'
'\n'
'$$\n'
'H = (\\mathcal{P}_1 \\circ \\mathcal{P}_2 \\circ \\cdots \\circ \\mathcal{P}_m)\n'
'$$\n'
'\n'
'where $\\mathcal{P}_i \\succ \\mathcal{P}_j$ means pattern $i$ *contains* pattern $j$\n'
'as a sub-component.  The key constraint is that **no two instances of the same\n'
'pattern may share mutable state** without an explicit synchronisation mechanism.\n'
))

# ═══════════════════════════════════════════════════════════════════════════════
# Cell 18 — Hybrid diagram (code)
# ═══════════════════════════════════════════════════════════════════════════════
cells.append(code(
'# ──────────────────────────────────────────────────────────────\n'
'#  Visualisation: Hybrid architecture diagram\n'
'# ──────────────────────────────────────────────────────────────\n'
'\n'
'fig, ax = plt.subplots(figsize=(14, 9))\n'
'H = nx.DiGraph()\n'
'\n'
'H.add_node("Top\\nSupervisor", layer="supervisor")\n'
'\n'
'consensus_groups = {\n'
'    "Topology\\nConsensus": ["Topo\\nAgent-a", "Topo\\nAgent-b", "Topo\\nArbiter"],\n'
'    "Sizing\\nConsensus": ["Size\\nAgent-a", "Size\\nAgent-b", "Size\\nArbiter"],\n'
'}\n'
'\n'
'for group, members in consensus_groups.items():\n'
'    H.add_node(group, layer="group")\n'
'    H.add_edge("Top\\nSupervisor", group)\n'
'    for m in members:\n'
'        H.add_node(m, layer="worker")\n'
'        H.add_edge(group, m)\n'
'\n'
'H.add_node("Sim\\nAgent", layer="oracle")\n'
'H.add_node("Layout\\nAgent", layer="worker")\n'
'H.add_edge("Top\\nSupervisor", "Sim\\nAgent")\n'
'H.add_edge("Top\\nSupervisor", "Layout\\nAgent")\n'
'H.add_edge("Sim\\nAgent", "Sizing\\nConsensus", label="handoff")\n'
'\n'
'pos = {\n'
'    "Top\\nSupervisor": (5, 4),\n'
'    "Topology\\nConsensus": (2, 2.5),\n'
'    "Sizing\\nConsensus": (5, 2.5),\n'
'    "Sim\\nAgent": (8, 2.5),\n'
'    "Layout\\nAgent": (10, 2.5),\n'
'    "Topo\\nAgent-a": (0.5, 1),\n'
'    "Topo\\nAgent-b": (2, 1),\n'
'    "Topo\\nArbiter": (3.5, 1),\n'
'    "Size\\nAgent-a": (4, 1),\n'
'    "Size\\nAgent-b": (5.5, 1),\n'
'    "Size\\nArbiter": (7, 1),\n'
'}\n'
'\n'
'layer_colors = {\n'
'    "supervisor": "#FF6B6B",\n'
'    "group": "#FFE66D",\n'
'    "worker": "#4ECDC4",\n'
'    "oracle": "#45B7D1",\n'
'}\n'
'\n'
'node_colors = []\n'
'for n in H.nodes():\n'
'    layer = H.nodes[n].get("layer", "worker")\n'
'    node_colors.append(layer_colors.get(layer, "#CCC"))\n'
'\n'
'node_sizes = [\n'
'    3500 if H.nodes[n].get("layer") == "supervisor"\n'
'    else 2800 if H.nodes[n].get("layer") == "group"\n'
'    else 2000\n'
'    for n in H.nodes()\n'
']\n'
'\n'
'regular_edges = [(u, v) for u, v, d in H.edges(data=True) if "label" not in d]\n'
'handoff_edges = [(u, v) for u, v, d in H.edges(data=True) if "label" in d]\n'
'\n'
'nx.draw_networkx_nodes(\n'
'    H, pos, node_color=node_colors, node_size=node_sizes,\n'
'    edgecolors="#333", linewidths=1.5, ax=ax,\n'
')\n'
'nx.draw_networkx_labels(H, pos, font_size=7, font_weight="bold", ax=ax)\n'
'nx.draw_networkx_edges(\n'
'    H, pos, edgelist=regular_edges, edge_color="#555",\n'
'    arrows=True, arrowsize=18, ax=ax, width=1.5,\n'
')\n'
'nx.draw_networkx_edges(\n'
'    H, pos, edgelist=handoff_edges, edge_color="#E74C3C",\n'
'    arrows=True, arrowsize=18, style="dashed",\n'
'    connectionstyle="arc3,rad=0.25", ax=ax, width=2,\n'
')\n'
'\n'
'legend_elems = [\n'
'    mpatches.Patch(facecolor="#FF6B6B", edgecolor="#333", label="Supervisor"),\n'
'    mpatches.Patch(facecolor="#FFE66D", edgecolor="#333", label="Consensus Group"),\n'
'    mpatches.Patch(facecolor="#4ECDC4", edgecolor="#333", label="Worker / Arbiter"),\n'
'    mpatches.Patch(facecolor="#45B7D1", edgecolor="#333", label="Simulation Oracle"),\n'
']\n'
'ax.legend(handles=legend_elems, loc="upper right", fontsize=9)\n'
'ax.set_title(\n'
'    "Hybrid Architecture — Supervisor + Consensus + Handoff",\n'
'    fontsize=14, fontweight="bold",\n'
')\n'
'ax.axis("off")\n'
'plt.tight_layout()\n'
'plt.show()\n'
))

# ═══════════════════════════════════════════════════════════════════════════════
# Cell 19 — Section 2.7 intro (markdown)
# ═══════════════════════════════════════════════════════════════════════════════
cells.append(md(
'---\n'
'\n'
'## 2.7 Agent Communication Protocols\n'
'\n'
'### Typed Messages for EDA Agents\n'
'\n'
'In production systems, agents must exchange **structured, versioned messages**\n'
'rather than free-form strings.  We use **Pydantic** models to enforce schemas\n'
'at both send and receive boundaries.\n'
'\n'
'**Design decisions:**\n'
'\n'
'| Approach | Pros | Cons |\n'
'|----------|------|------|\n'
'| **Shared state (blackboard)** | Simple reads; single source of truth | Concurrency hazards; tight coupling |\n'
'| **Message passing** | Loose coupling; auditable history | Serialisation overhead; ordering complexity |\n'
'| **Hybrid** | Best of both worlds | Implementation complexity |\n'
'\n'
'> **Recommendation for analog EDA:** Use message passing for inter-stage\n'
'> communication and a shared state object (with versioning) for the current\n'
'> design context (netlist, constraints, PPA).\n'
'\n'
'### Protocol Requirements\n'
'\n'
'A well-designed agent communication protocol must satisfy:\n'
'\n'
'1. **Type safety** — every field has a declared type and validated at runtime\n'
'2. **Correlation** — request-response pairs share a `correlation_id`\n'
'3. **Traceability** — every message carries a timestamp and unique ID\n'
'4. **Extensibility** — new message types can be added without breaking existing agents\n'
'5. **Serialisability** — messages can be persisted to JSON / Protobuf for replay\n'
))

# ═══════════════════════════════════════════════════════════════════════════════
# Cell 20 — Pydantic models (code)
# ═══════════════════════════════════════════════════════════════════════════════
cells.append(code(
'# ──────────────────────────────────────────────────────────────\n'
'#  Agent Communication: Pydantic message models\n'
'# ──────────────────────────────────────────────────────────────\n'
'\n'
'class MessageType(str, enum.Enum):\n'
'    TASK_DISPATCH = "task_dispatch"\n'
'    TASK_RESULT = "task_result"\n'
'    HANDOFF = "handoff"\n'
'    STATUS_UPDATE = "status_update"\n'
'    PPA_REPORT = "ppa_report"\n'
'    ERROR = "error"\n'
'\n'
'\n'
'class PPAPayload(BaseModel):\n'
'    """PPA metrics as a Pydantic model for serialisation."""\n'
'\n'
'    power_mw: float = Field(..., ge=0, description="Power in milliwatts")\n'
'    frequency_mhz: float = Field(..., ge=0, description="Clock frequency in MHz")\n'
'    area_um2: float = Field(..., ge=0, description="Die area in um2")\n'
'\n'
'    @property\n'
'    def score(self) -> float:\n'
'        return (self.power_mw * self.area_um2) / max(self.frequency_mhz, 1e-9)\n'
'\n'
'\n'
'class AgentMessage(BaseModel):\n'
'    """Typed, validated message exchanged between EDA agents."""\n'
'\n'
'    message_id: str = Field(default_factory=lambda: uuid.uuid4().hex[:10])\n'
'    msg_type: MessageType\n'
'    sender: str\n'
'    receiver: str\n'
'    payload: dict[str, Any] = Field(default_factory=dict)\n'
'    ppa: Optional[PPAPayload] = None\n'
'    timestamp: str = Field(\n'
'        default_factory=lambda: datetime.now(timezone.utc).isoformat()\n'
'    )\n'
'    correlation_id: Optional[str] = Field(\n'
'        default=None,\n'
'        description="Links request-response pairs",\n'
'    )\n'
'\n'
'\n'
'# ── Demonstrate serialisation round-trip ──\n'
'msg = AgentMessage(\n'
'    msg_type=MessageType.PPA_REPORT,\n'
'    sender="SizingAgent",\n'
'    receiver="Supervisor",\n'
'    payload={"topology": "folded_cascode", "gain_dB": 62.5},\n'
'    ppa=PPAPayload(power_mw=1.1, frequency_mhz=850, area_um2=42000),\n'
')\n'
'\n'
'print("-- Serialised message (JSON) --")\n'
'print(msg.model_dump_json(indent=2))\n'
'\n'
'# Round-trip: deserialise and verify\n'
'msg_roundtrip = AgentMessage.model_validate_json(msg.model_dump_json())\n'
'assert msg_roundtrip.message_id == msg.message_id\n'
'print(f"\\nPPA score = {msg.ppa.score:.2f}")\n'
'print("Round-trip serialisation verified.")\n'
))

# ═══════════════════════════════════════════════════════════════════════════════
# Cell 21 — Message Bus (code)
# ═══════════════════════════════════════════════════════════════════════════════
cells.append(code(
'# ──────────────────────────────────────────────────────────────\n'
'#  Simple Event-Based Message Bus\n'
'# ──────────────────────────────────────────────────────────────\n'
'\n'
'class MessageBus:\n'
'    """Publish-subscribe message bus for agent communication."""\n'
'\n'
'    def __init__(self) -> None:\n'
'        self._subscribers: dict[str, list[Callable[[AgentMessage], None]]] = {}\n'
'        self._history: list[AgentMessage] = []\n'
'\n'
'    def subscribe(\n'
'        self, agent_name: str, handler: Callable[[AgentMessage], None]\n'
'    ) -> None:\n'
'        self._subscribers.setdefault(agent_name, []).append(handler)\n'
'\n'
'    def publish(self, message: AgentMessage) -> None:\n'
'        self._history.append(message)\n'
'        handlers = self._subscribers.get(message.receiver, [])\n'
'        for h in handlers:\n'
'            h(message)\n'
'\n'
'    def get_history(\n'
'        self, agent_name: str | None = None\n'
'    ) -> list[AgentMessage]:\n'
'        if agent_name is None:\n'
'            return list(self._history)\n'
'        return [\n'
'            m for m in self._history\n'
'            if m.sender == agent_name or m.receiver == agent_name\n'
'        ]\n'
'\n'
'    @property\n'
'    def total_messages(self) -> int:\n'
'        return len(self._history)\n'
'\n'
'\n'
'# ── Demo ──\n'
'bus = MessageBus()\n'
'received: list[str] = []\n'
'\n'
'\n'
'def supervisor_handler(msg: AgentMessage) -> None:\n'
'    received.append(f"Supervisor got {msg.msg_type} from {msg.sender}")\n'
'\n'
'\n'
'bus.subscribe("Supervisor", supervisor_handler)\n'
'\n'
'for agent in ["SynthAgent", "DFTAgent", "STAAgent"]:\n'
'    bus.publish(\n'
'        AgentMessage(\n'
'            msg_type=MessageType.TASK_RESULT,\n'
'            sender=agent,\n'
'            receiver="Supervisor",\n'
'            payload={"status": "done", "worker": agent},\n'
'        )\n'
'    )\n'
'\n'
'print("Messages delivered to Supervisor:")\n'
'for r in received:\n'
'    print(f"  * {r}")\n'
'print(f"\\nTotal messages on bus: {bus.total_messages}")\n'
))

# ═══════════════════════════════════════════════════════════════════════════════
# Cell 22 — Section 2.8 intro (markdown)
# ═══════════════════════════════════════════════════════════════════════════════
cells.append(md(
'---\n'
'\n'
'## 2.8 Practical Exercise: Build a Mini Analog Design MAS\n'
'\n'
'> **Objective:** Wire together a four-agent pipeline that takes a\n'
'> textual specification and produces a (mock) verified circuit design.\n'
'\n'
'### System Architecture\n'
'\n'
'| Agent | Role | Input | Output |\n'
'|-------|------|-------|--------|\n'
'| `SpecParser` | Extract structured spec from natural language | Raw spec string | `DesignSpec` dict |\n'
'| `TopologySelector` | Choose optimal circuit topology | `DesignSpec` | Topology + rationale |\n'
'| `CircuitSizer` | Determine transistor dimensions | Topology + spec | Sized netlist |\n'
'| `SimulationOracle` | Verify design via mock SPICE | Sized netlist | Pass / Fail + metrics |\n'
'\n'
'The pipeline uses a combination of:\n'
'- **Supervisor** dispatch (orchestration)\n'
'- **Handoff** semantics (fail → retry with updated topology)\n'
'- **Typed messages** (Pydantic `AgentMessage`)\n'
'\n'
'Output is rendered with the **`rich`** library for clear, coloured console output.\n'
'\n'
'### Convergence Analysis\n'
'\n'
'The pipeline terminates when either:\n'
'\n'
'$$\n'
'\\text{gain}_{\\text{sim}} \\geq \\text{gain}_{\\text{target}} \\;\\wedge\\;\n'
'\\text{GBW}_{\\text{sim}} \\geq 0.9 \\cdot \\text{GBW}_{\\text{target}} \\;\\wedge\\;\n'
'\\text{PM} \\geq 45^\\circ\n'
'$$\n'
'\n'
'or the maximum iteration count $N_{\\max} = 4$ is reached.\n'
))

# ═══════════════════════════════════════════════════════════════════════════════
# Cell 23 — Mini MAS agents (code)
# ═══════════════════════════════════════════════════════════════════════════════
cells.append(code(
'# ──────────────────────────────────────────────────────────────\n'
'#  Mini Analog Design MAS — Agent Implementations\n'
'# ──────────────────────────────────────────────────────────────\n'
'\n'
'from rich.console import Console\n'
'from rich.panel import Panel\n'
'from rich.table import Table\n'
'from rich import box\n'
'\n'
'console = Console(width=90)\n'
'\n'
'\n'
'@dataclass\n'
'class DesignSpec:\n'
'    """Parsed design specification."""\n'
'\n'
'    circuit_type: str = ""\n'
'    gain_db: float = 0.0\n'
'    gbw_mhz: float = 0.0\n'
'    load_pf: float = 0.0\n'
'    supply_v: float = 0.0\n'
'    technology_nm: int = 0\n'
'\n'
'\n'
'@dataclass\n'
'class SizedNetlist:\n'
'    """Transistor-level sizing results."""\n'
'\n'
'    topology: str = ""\n'
'    devices: dict[str, dict[str, float]] = field(default_factory=dict)\n'
'    bias_current_ua: float = 0.0\n'
'\n'
'\n'
'@dataclass\n'
'class SimResult:\n'
'    """Simulation verification result."""\n'
'\n'
'    passed: bool = False\n'
'    gain_db: float = 0.0\n'
'    gbw_mhz: float = 0.0\n'
'    phase_margin_deg: float = 0.0\n'
'    power_mw: float = 0.0\n'
'\n'
'\n'
'class SpecParserMAS:\n'
'    """Extracts structured specs from natural-language input."""\n'
'\n'
'    name = "SpecParser"\n'
'\n'
'    def run(self, raw_spec: str) -> DesignSpec:\n'
'        spec = DesignSpec(\n'
'            circuit_type="Operational Transconductance Amplifier",\n'
'            gain_db=60.0,\n'
'            gbw_mhz=100.0,\n'
'            load_pf=2.0,\n'
'            supply_v=1.8,\n'
'            technology_nm=180,\n'
'        )\n'
'        console.print(Panel(\n'
'            f"[bold]Parsed specification:[/bold]\\n"\n'
'            f"  Circuit  : {spec.circuit_type}\\n"\n'
'            f"  Gain     : {spec.gain_db} dB\\n"\n'
'            f"  GBW      : {spec.gbw_mhz} MHz\\n"\n'
'            f"  C_L      : {spec.load_pf} pF\\n"\n'
'            f"  V_DD     : {spec.supply_v} V\\n"\n'
'            f"  Tech     : {spec.technology_nm} nm",\n'
'            title=f"[cyan]{self.name}[/cyan]",\n'
'            border_style="cyan",\n'
'        ))\n'
'        return spec\n'
'\n'
'\n'
'class TopologySelectorMAS:\n'
'    """Selects circuit topology based on spec requirements."""\n'
'\n'
'    name = "TopologySelector"\n'
'\n'
'    TOPOLOGIES = {\n'
'        "telescopic": {"max_gain_db": 55, "speed": "fast", "swing": "low"},\n'
'        "folded_cascode": {"max_gain_db": 70, "speed": "medium", "swing": "medium"},\n'
'        "two_stage_miller": {"max_gain_db": 90, "speed": "slow", "swing": "high"},\n'
'    }\n'
'\n'
'    def run(self, spec: DesignSpec, iteration: int = 0) -> str:\n'
'        candidates = list(self.TOPOLOGIES.keys())\n'
'        chosen = candidates[-1]\n'
'        for name, props in self.TOPOLOGIES.items():\n'
'            if props["max_gain_db"] >= spec.gain_db:\n'
'                chosen = name\n'
'                break\n'
'\n'
'        if iteration > 0:\n'
'            idx = min(candidates.index(chosen) + iteration, len(candidates) - 1)\n'
'            chosen = candidates[idx]\n'
'\n'
'        props = self.TOPOLOGIES[chosen]\n'
'        console.print(Panel(\n'
'            f"[bold]Selected:[/bold] {chosen.replace(\'_\', \' \').title()}\\n"\n'
'            f"  Max gain   : {props[\'max_gain_db\']} dB\\n"\n'
'            f"  Speed      : {props[\'speed\']}\\n"\n'
'            f"  Output swing: {props[\'swing\']}\\n"\n'
'            f"  Iteration  : {iteration}",\n'
'            title=f"[green]{self.name}[/green]",\n'
'            border_style="green",\n'
'        ))\n'
'        return chosen\n'
'\n'
'\n'
'class CircuitSizerMAS:\n'
'    """Determines transistor dimensions for the chosen topology."""\n'
'\n'
'    name = "CircuitSizer"\n'
'\n'
'    def run(self, topology: str, spec: DesignSpec) -> SizedNetlist:\n'
'        base_w = {"telescopic": 10, "folded_cascode": 20, "two_stage_miller": 15}\n'
'        w = base_w.get(topology, 15)\n'
'        netlist = SizedNetlist(\n'
'            topology=topology,\n'
'            devices={\n'
'                "M1_input": {\n'
'                    "W_um": round(w * random.uniform(0.8, 1.2), 1),\n'
'                    "L_um": spec.technology_nm / 1000,\n'
'                },\n'
'                "M3_load": {\n'
'                    "W_um": round(w * 0.5 * random.uniform(0.8, 1.2), 1),\n'
'                    "L_um": spec.technology_nm / 1000,\n'
'                },\n'
'                "M5_tail": {\n'
'                    "W_um": round(w * 1.5 * random.uniform(0.8, 1.2), 1),\n'
'                    "L_um": spec.technology_nm / 1000 * 2,\n'
'                },\n'
'                "M7_cascode": {\n'
'                    "W_um": round(w * random.uniform(0.8, 1.2), 1),\n'
'                    "L_um": spec.technology_nm / 1000,\n'
'                },\n'
'            },\n'
'            bias_current_ua=round(random.uniform(50, 200), 1),\n'
'        )\n'
'\n'
'        table = Table(title="Sized Netlist", box=box.ROUNDED)\n'
'        table.add_column("Device", style="bold")\n'
'        table.add_column("W (um)", justify="right")\n'
'        table.add_column("L (um)", justify="right")\n'
'        for dev, params in netlist.devices.items():\n'
'            table.add_row(dev, f"{params[\'W_um\']:.1f}", f"{params[\'L_um\']:.3f}")\n'
'        table.add_row("I_bias", f"{netlist.bias_current_ua:.1f} uA", "---")\n'
'\n'
'        console.print(Panel(\n'
'            table,\n'
'            title=f"[yellow]{self.name}[/yellow]",\n'
'            border_style="yellow",\n'
'        ))\n'
'        return netlist\n'
'\n'
'\n'
'class SimulationOracleMAS:\n'
'    """Mock SPICE simulation oracle."""\n'
'\n'
'    name = "SimOracle"\n'
'\n'
'    def run(self, netlist: SizedNetlist, spec: DesignSpec) -> SimResult:\n'
'        topo_factor = {\n'
'            "telescopic": 0.85,\n'
'            "folded_cascode": 0.95,\n'
'            "two_stage_miller": 1.05,\n'
'        }.get(netlist.topology, 0.9)\n'
'\n'
'        result = SimResult(\n'
'            passed=False,\n'
'            gain_db=round(\n'
'                spec.gain_db * topo_factor * random.uniform(0.9, 1.1), 1\n'
'            ),\n'
'            gbw_mhz=round(spec.gbw_mhz * random.uniform(0.85, 1.15), 1),\n'
'            phase_margin_deg=round(random.uniform(45, 75), 1),\n'
'            power_mw=round(\n'
'                netlist.bias_current_ua * spec.supply_v / 1000\n'
'                * random.uniform(0.8, 1.2),\n'
'                3,\n'
'            ),\n'
'        )\n'
'        result.passed = (\n'
'            result.gain_db >= spec.gain_db\n'
'            and result.gbw_mhz >= spec.gbw_mhz * 0.9\n'
'            and result.phase_margin_deg >= 45\n'
'        )\n'
'\n'
'        status = (\n'
'            "[bold green]PASS[/bold green]"\n'
'            if result.passed\n'
'            else "[bold red]FAIL[/bold red]"\n'
'        )\n'
'        console.print(Panel(\n'
'            f"  Status       : {status}\\n"\n'
'            f"  Gain         : {result.gain_db:.1f} dB  "\n'
'            f"(target >= {spec.gain_db})\\n"\n'
'            f"  GBW          : {result.gbw_mhz:.1f} MHz "\n'
'            f"(target >= {spec.gbw_mhz})\\n"\n'
'            f"  Phase margin : {result.phase_margin_deg:.1f} deg\\n"\n'
'            f"  Power        : {result.power_mw:.3f} mW",\n'
'            title=f"[magenta]{self.name}[/magenta]",\n'
'            border_style="magenta",\n'
'        ))\n'
'        return result\n'
'\n'
'\n'
'print("All pipeline agents defined.")\n'
))

# ═══════════════════════════════════════════════════════════════════════════════
# Cell 24 — Pipeline execution (code)
# ═══════════════════════════════════════════════════════════════════════════════
cells.append(code(
'# ──────────────────────────────────────────────────────────────\n'
'#  End-to-End Pipeline Execution\n'
'# ──────────────────────────────────────────────────────────────\n'
'\n'
'\n'
'def run_analog_design_pipeline(\n'
'    raw_spec: str, max_iterations: int = 4\n'
') -> None:\n'
'    """Execute the full mini analog design MAS."""\n'
'    console.rule("[bold blue]Mini Analog Design MAS — Pipeline Start[/bold blue]")\n'
'\n'
'    parser = SpecParserMAS()\n'
'    topo_selector = TopologySelectorMAS()\n'
'    sizer = CircuitSizerMAS()\n'
'    sim_oracle = SimulationOracleMAS()\n'
'\n'
'    spec = parser.run(raw_spec)\n'
'\n'
'    for iteration in range(max_iterations):\n'
'        console.rule(f"[bold]Iteration {iteration}[/bold]")\n'
'\n'
'        topology = topo_selector.run(spec, iteration=iteration)\n'
'        netlist = sizer.run(topology, spec)\n'
'        result = sim_oracle.run(netlist, spec)\n'
'\n'
'        if result.passed:\n'
'            console.rule("[bold green]DESIGN CONVERGED[/bold green]")\n'
'\n'
'            summary = Table(\n'
'                title="Final Design Summary", box=box.DOUBLE_EDGE\n'
'            )\n'
'            summary.add_column("Metric", style="bold")\n'
'            summary.add_column("Value", justify="right")\n'
'            summary.add_row(\n'
'                "Topology", topology.replace("_", " ").title()\n'
'            )\n'
'            summary.add_row("Gain", f"{result.gain_db:.1f} dB")\n'
'            summary.add_row("GBW", f"{result.gbw_mhz:.1f} MHz")\n'
'            summary.add_row(\n'
'                "Phase Margin", f"{result.phase_margin_deg:.1f} deg"\n'
'            )\n'
'            summary.add_row("Power", f"{result.power_mw:.3f} mW")\n'
'            summary.add_row("Iterations", str(iteration + 1))\n'
'            console.print(summary)\n'
'            return\n'
'\n'
'        console.print(\n'
'            f"  [red]Handoff: SimOracle -> TopologySelector "\n'
'            f"(gain = {result.gain_db:.1f} dB < {spec.gain_db} dB)[/red]\\n"\n'
'        )\n'
'\n'
'    console.rule(\n'
'        "[bold red]MAX ITERATIONS REACHED — DESIGN NOT CONVERGED[/bold red]"\n'
'    )\n'
'\n'
'\n'
'# ── Execute ──\n'
'run_analog_design_pipeline(\n'
'    "Design a folded-cascode OTA with 60 dB gain, 100 MHz GBW, "\n'
'    "2 pF load in 180 nm CMOS at 1.8 V supply."\n'
')\n'
))

# ═══════════════════════════════════════════════════════════════════════════════
# Cell 25 — Summary (markdown)
# ═══════════════════════════════════════════════════════════════════════════════
cells.append(md(
'---\n'
'\n'
'## Summary and Key Takeaways\n'
'\n'
'### The Four Canonical MAS Patterns\n'
'\n'
'| # | Pattern | Core Idea | Best For |\n'
'|---|---------|-----------|----------|\n'
'| 1 | **Supervisor-Worker** | Central dispatch, parallel execution | Task decomposition |\n'
'| 2 | **Consensus-Based Reasoning** | Divergent proposals, arbiter selection | Non-convex search spaces |\n'
'| 3 | **Handoff** | Dynamic re-routing with error context | Iterative refinement |\n'
'| 4 | **Stateful Graph Workflows** | DAG / cyclic execution graphs | Complex multi-stage flows |\n'
'\n'
'### Key Equations\n'
'\n'
'| Equation | Meaning |\n'
'|----------|---------|\n'
'| $C = \\binom{n}{2}$ | Communication channels in unstructured MAS |\n'
'| $J(P_i) = \\alpha\\hat{p}_i + \\beta(1-\\hat{f}_i) + \\gamma\\hat{a}_i$ | Weighted PPA objective |\n'
'| $P^* = \\arg\\min_i J(P_i)$ | Consensus winner selection |\n'
'| $\\text{PPA}_{\\text{score}} = \\frac{P \\cdot A}{f}$ | Unified PPA figure of merit |\n'
'| $\\phi(s) = \\bigwedge_c [s_c \\geq t_c]$ | Convergence predicate for cyclic graphs |\n'
'\n'
'### Design Principles\n'
'\n'
'1. **Start simple** — Supervisor-Worker handles 80% of use cases\n'
'2. **Add consensus** when topology/architecture decisions have high uncertainty\n'
'3. **Use handoffs** when iterative refinement with domain experts is needed\n'
'4. **Graduate to DAGs** when the flow has complex conditional branching\n'
'5. **Combine patterns** hierarchically for production systems\n'
'6. **Always use typed messages** — free-form strings are a liability\n'
'\n'
'### What\'s Next\n'
'\n'
'In **Chapter 3**, we will implement these patterns using **LangGraph** — a\n'
'production framework that provides first-class support for stateful,\n'
'graph-based agent workflows with persistence, human-in-the-loop\n'
'checkpoints, and streaming.\n'
'\n'
'---\n'
'\n'
'> *"Architecture is the art of how to waste space."* — Philip Johnson  \n'
'> *"Agent architecture is the art of how to **not** waste compute."* — This course\n'
))

# ═══════════════════════════════════════════════════════════════════════════════
# Cell 26 — References (markdown)
# ═══════════════════════════════════════════════════════════════════════════════
cells.append(md(
'---\n'
'\n'
'## References and Further Reading\n'
'\n'
'1. **Gamma, E., Helm, R., Johnson, R., & Vlissides, J.** (1994).\n'
'   *Design Patterns: Elements of Reusable Object-Oriented Software.*\n'
'   Addison-Wesley.\n'
'\n'
'2. **Wooldridge, M.** (2009). *An Introduction to MultiAgent Systems* (2nd ed.).\n'
'   John Wiley & Sons.\n'
'\n'
'3. **Ferber, J.** (1999). *Multi-Agent Systems: An Introduction to Distributed\n'
'   Artificial Intelligence.* Addison-Wesley.\n'
'\n'
'4. **Gielen, G. & Rutenbar, R.** (2000). Computer-aided design of analog and\n'
'   mixed-signal integrated circuits. *Proceedings of the IEEE*, 88(12), 1825–1854.\n'
'\n'
'5. **LangGraph Documentation.** (2025). *Stateful, graph-based agent workflows.*\n'
'   https://langchain-ai.github.io/langgraph/\n'
'\n'
'6. **Anthropic.** (2025). *Building effective agents.*\n'
'   https://docs.anthropic.com/en/docs/build-with-claude/agentic\n'
'\n'
'7. **Razavi, B.** (2017). *Design of Analog CMOS Integrated Circuits* (2nd ed.).\n'
'   McGraw-Hill.\n'
'\n'
'8. **Allen, P. E., & Holberg, D. R.** (2012). *CMOS Analog Circuit Design*\n'
'   (3rd ed.). Oxford University Press.\n'
'\n'
'---\n'
'\n'
'**End of Chapter 2**\n'
))

# ═══════════════════════════════════════════════════════════════════════════════
# Assemble notebook
# ═══════════════════════════════════════════════════════════════════════════════
notebook = {
    "nbformat": 4,
    "nbformat_minor": 5,
    "metadata": {
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3",
        },
        "language_info": {
            "name": "python",
            "version": "3.11.0",
            "mimetype": "text/x-python",
            "file_extension": ".py",
        },
    },
    "cells": cells,
}

out_dir = pathlib.Path(
    "/workspace/2AB- Multi-Agent Analog EDA/"
    "Chapter 02 - Core Agentic Architectures"
)
out_dir.mkdir(parents=True, exist_ok=True)
out_path = out_dir / "02_agentic_architectures.ipynb"

with open(out_path, "w", encoding="utf-8") as f:
    json.dump(notebook, f, indent=1, ensure_ascii=False)

print(f"Notebook written to {out_path}")
print(f"  Total cells: {len(cells)}")
print(f"  Markdown cells: {sum(1 for c in cells if c['cell_type'] == 'markdown')}")
print(f"  Code cells: {sum(1 for c in cells if c['cell_type'] == 'code')}")
